spring:
    application:
        name: normal-project
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://172.20.160.120:3308/normal
#        url: jdbc:mysql://172.20.160.120:3309/normal
#        url: jdbc:mysql://10.96.100.155:3309/normal
        username: root
        password: 1qaz2wsx

mybatis:
    mapperLocations: classpath:mapper/*.xml

#logging:
#    level:
#        root: DEBUG