spring:
    application:
        name: normal-project
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://172.20.160.120:3308/normal
#        url: jdbc:mysql://172.20.160.120:3309/normal
#        url: jdbc:mysql://10.96.100.155:3309/normal
        username: root
        password: 1qaz2wsx

    # influx:
    #     url: http://172.20.160.120:8086
    #     token: hxnhyjsGC7FBmzOAvWU2yOUXqY81bt70IWznX2AcACGXWhGw5Kna7JvEoEOMcBfsXIB76A9NFBlrcvWYg73KTw==
    #     org: caster-Orgo
    #     bucket: caster-bucket

mybatis:
    mapperLocations: classpath:mapper/*.xml

#logging:
#    level:
#        root: DEBUG


#management:
#    metrics:
#        export:
#            influx:
#                uri: http://172.20.160.120:8086
#                userName: casterbasic
#                password: 1qaz2wsx
##                token: hxnhyjsGC7FBmzOAvWU2yOUXqY81bt70IWznX2AcACGXWhGw5Kna7JvEoEOMcBfsXIB76A9NFBlrcvWYg73KTw==
#                connect-timeout: 5
#                read-timeout: 5
#                db: caster-bucket
